### ISSUE TITLE
Typo breaks this package

### ISSUE THREAD

**Issue by cspeer** [WilliamDASILVA/vue-browserupdate#4]
Hi,

there is a typo here: https://github.com/WilliamDASILVA/vue-browserupdate/blob/master/dist/index.js#L14 which unfortunately breaks the whole package upon import. Would you mind fixing and releasing it? :)

Thanks,
Chris

**Comment by thmsnhl** [comment]
@cspeer and anyone who stumbles upon this issue: we have forked the project and created a fix + updated the browserupdate dependency to match the current version.
Feel free to use it: https://www.npmjs.com/package/@sum.cumo/vue-browserupdate

**Comment by cspeer** [comment]
awesome. thanks @thmsnhl
